fix(ui-library): align hint and error message icons
deven-org/boiler pull request #1059
Opened 2024-03-27 09:38 UTC by RubirajAccenture

2024-03-27 11:15 UTC, davidken91 approved these changes

2024-03-27 11:57 UTC, angsherpa456 commented on packages/ui-library/src/components/checkbox/index.test.ts
> +  it('has error Icon is set to undefined', async () => {
Please adjust it to it('has error Icon set to undefined'...) [remove 'is' as we discussed yesterday]

2024-03-27 11:58 UTC, angsherpa456 commented on packages/ui-library/src/components/input-field-text/index.test.ts
> +
Please remove this extra new line.

2024-03-27 11:58 UTC, angsherpa456 commented on packages/ui-library/src/components/radio-group/index.test.ts
> +        hasError: false,
hasError needs to be true

2024-03-27 11:59 UTC, angsherpa456 commented on packages/ui-library/src/components/radio/index.test.ts
> +        hasError: false,
hasError needs to be true

2024-03-27 12:00 UTC, angsherpa456 commented on packages/ui-library/src/components/radio/index.test.ts
> +
This extra new line can be removed for the consistency purpose. Right now they are mixed up.

2024-03-27 12:00 UTC, angsherpa456 commented on packages/ui-library/src/components/textarea/index.test.ts
> +
Please remove this extra new line.

2024-03-27 15:57 UTC, thrbnhrtmnn requested changes
Hey @RubirajAccenture , I just found one small thing. If I set the Input Field Text component to "hasError"=true, I see a blrInfo icon. This should not be there, the default icon should be undefined. Please also check that the test that you implemented also works and finds this issue.

2024-03-28 11:02 UTC, angsherpa456 approved these changes
LGTM

2024-03-28 11:35 UTC, davidken91 approved these changes

2024-04-02 11:45 UTC, thrbnhrtmnn approved these changes
Approved

2024-04-02 11:45 UTC, merged