fix(ui-library): align counter to right for text area with or without error
deven-org/boiler pull request #1105
Opened 2024-05-21 09:42 UTC by ashk1996

closes #1064

2024-05-22 10:25 UTC, angsherpa456 commented on packages/ui-library/src/components/textarea/index.css.ts
> +  .blr-textarea-info-container.error {
For consistency, please follow the similar pattern like other:
.blr-textarea-info-container {
&.error {...}
&.hit {...}
}

2024-05-22 10:33 UTC, angsherpa456 commented on packages/ui-library/src/components/textarea/index.css.ts
> +  }
Seems like your branch is out of sync with develop branch, please fix that and will approve it. Also please remove this extra space at line 43.

2024-05-22 10:40 UTC, angsherpa456 approved these changes
LGTM

2024-05-23 07:24 UTC, thrbnhrtmnn requested changes
I just had a quick look and found one issue. If you add an error message and error message icon, they are right aligned, but they should be left aligned. 
<img width="350" alt="Screenshot 2024-05-23 at 09 20 46" src="https://github.com/deven-org/boiler/assets/122102805/38ebbafd-398b-4e2a-ba95-cf652989d9fc">

Here is how it should look according to design: 
<img width="301" alt="Screenshot 2024-05-23 at 09 24 36" src="https://github.com/deven-org/boiler/assets/122102805/0ffae63a-a29f-4bd9-9119-98d0764b0476">

2024-05-23 08:08 UTC, ashk1996 commented
> I just had a quick look and found one issue. If you add an error message and error message icon, they are right aligned, but they should be left aligned. <img alt="Screenshot 2024-05-23 at 09 20 46" width="350" src="https://private-user-images.githubusercontent.com/122102805/333080035-38ebbafd-398b-4e2a-ba95-cf652989d9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3MzEsIm5iZiI6MTcxNjQ1MTQzMSwicGF0aCI6Ii8xMjIxMDI4MDUvMzMzMDgwMDM1LTM4ZWJiYWZkLTM5OGItNGUyYS1iYTk1LWNmNjUyOTg5ZDlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmEyMGE3ZDg1YzViOWVmYmU3NDMxNjI4MTM3NzhmMTYxNDZiOTIyMjYyZjYxMTlhMTc0NDg5NzZjMTZmYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aq34X3hi0-Do-ww7NtpbCC5mpOUKlMCcErYvdLRb-Qs">
> 
> Here is how it should look according to design: <img alt="Screenshot 2024-05-23 at 09 24 36" width="301" src="https://private-user-images.githubusercontent.com/122102805/333080990-0ffae63a-a29f-4bd9-9119-98d0764b0476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3MzEsIm5iZiI6MTcxNjQ1MTQzMSwicGF0aCI6Ii8xMjIxMDI4MDUvMzMzMDgwOTkwLTBmZmFlNjNhLWEyOWYtNGJkOS05MTE5LTk4ZDA3NjRiMDQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWU2ZjE3NzkxNDg2YTY0OWYwZjY2ZWZjNzQ4NDQyYWFiZjczYmRlNDk0MjU2YWRiNWRkMThhM2YzNDQ3NzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.psL7Z9LZA4Gzys6gU1gWjCErdro0_mZIYFFkVMG9RA8">

Hi @thrbnhrtmnn 
Just doubled checked, I see that it is left aligned. 
<img width="1143" alt="Screenshot 2024-05-23 at 10 08 13" src="https://github.com/deven-org/boiler/assets/125904756/e1b98715-3de7-47ed-90b5-2832b5f75c6d">

2024-05-24 15:57 UTC, thrbnhrtmnn commented
> > I just had a quick look and found one issue. If you add an error message and error message icon, they are right aligned, but they should be left aligned. <img alt="Screenshot 2024-05-23 at 09 20 46" width="350" src="https://private-user-images.githubusercontent.com/122102805/333080035-38ebbafd-398b-4e2a-ba95-cf652989d9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3MzEsIm5iZiI6MTcxNjQ1MTQzMSwicGF0aCI6Ii8xMjIxMDI4MDUvMzMzMDgwMDM1LTM4ZWJiYWZkLTM5OGItNGUyYS1iYTk1LWNmNjUyOTg5ZDlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmEyMGE3ZDg1YzViOWVmYmU3NDMxNjI4MTM3NzhmMTYxNDZiOTIyMjYyZjYxMTlhMTc0NDg5NzZjMTZmYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aq34X3hi0-Do-ww7NtpbCC5mpOUKlMCcErYvdLRb-Qs">
> > Here is how it should look according to design: <img alt="Screenshot 2024-05-23 at 09 24 36" width="301" src="https://private-user-images.githubusercontent.com/122102805/333080990-0ffae63a-a29f-4bd9-9119-98d0764b0476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3MzEsIm5iZiI6MTcxNjQ1MTQzMSwicGF0aCI6Ii8xMjIxMDI4MDUvMzMzMDgwOTkwLTBmZmFlNjNhLWEyOWYtNGJkOS05MTE5LTk4ZDA3NjRiMDQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWU2ZjE3NzkxNDg2YTY0OWYwZjY2ZWZjNzQ4NDQyYWFiZjczYmRlNDk0MjU2YWRiNWRkMThhM2YzNDQ3NzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.psL7Z9LZA4Gzys6gU1gWjCErdro0_mZIYFFkVMG9RA8">
> 
> Hi @thrbnhrtmnn Just doubled checked, I see that it is left aligned. <img alt="Screenshot 2024-05-23 at 10 08 13" width="1143" src="https://private-user-images.githubusercontent.com/125904756/333095897-e1b98715-3de7-47ed-90b5-2832b5f75c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjYzNTAsIm5iZiI6MTcxNjU2NjA1MCwicGF0aCI6Ii8xMjU5MDQ3NTYvMzMzMDk1ODk3LWUxYjk4NzE1LTNkZTctNDdlZC05MGI1LTI4MzJiNWY3NWM2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTU0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjBhNjUzNDY0Mzc3OTJhMGZmNWY5MjE1NjkwYzNmMTQ0MWQyZDZkMzFlNGQyZWFkZTExMTliZDgxNmQwOGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t0zMe89pMBx3YsTGqNaD_tblmz6Y8JMfVUgmQW4VXIg">

Hey @ashk1996 , in your example hasHint = true. In this case it looks good. But if hasHint = false and only hasError = true and errorMessage is not empty, then the error message is not left aligned but right aligned, as seen in my screenshot above. 

While looking at it again, if errorMessageIcon is not undefined and errorMessage is empty, the icon should also be displayed right aligned, but currently it is not displayed at all in this case. It will only appear once errorMessage is not empty anymore.

If you want we can have a quick huddle about this :-)

2024-05-27 16:53 UTC, ashk1996 commented
> > > I just had a quick look and found one issue. If you add an error message and error message icon, they are right aligned, but they should be left aligned. <img alt="Screenshot 2024-05-23 at 09 20 46" width="350" src="https://private-user-images.githubusercontent.com/122102805/333080035-38ebbafd-398b-4e2a-ba95-cf652989d9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3MzEsIm5iZiI6MTcxNjQ1MTQzMSwicGF0aCI6Ii8xMjIxMDI4MDUvMzMzMDgwMDM1LTM4ZWJiYWZkLTM5OGItNGUyYS1iYTk1LWNmNjUyOTg5ZDlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmEyMGE3ZDg1YzViOWVmYmU3NDMxNjI4MTM3NzhmMTYxNDZiOTIyMjYyZjYxMTlhMTc0NDg5NzZjMTZmYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aq34X3hi0-Do-ww7NtpbCC5mpOUKlMCcErYvdLRb-Qs">
> > > Here is how it should look according to design: <img alt="Screenshot 2024-05-23 at 09 24 36" width="301" src="https://private-user-images.githubusercontent.com/122102805/333080990-0ffae63a-a29f-4bd9-9119-98d0764b0476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3MzEsIm5iZiI6MTcxNjQ1MTQzMSwicGF0aCI6Ii8xMjIxMDI4MDUvMzMzMDgwOTkwLTBmZmFlNjNhLWEyOWYtNGJkOS05MTE5LTk4ZDA3NjRiMDQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWU2ZjE3NzkxNDg2YTY0OWYwZjY2ZWZjNzQ4NDQyYWFiZjczYmRlNDk0MjU2YWRiNWRkMThhM2YzNDQ3NzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.psL7Z9LZA4Gzys6gU1gWjCErdro0_mZIYFFkVMG9RA8">
> > 
> > 
> > Hi @thrbnhrtmnn Just doubled checked, I see that it is left aligned. <img alt="Screenshot 2024-05-23 at 10 08 13" width="1143" src="https://private-user-images.githubusercontent.com/125904756/333095897-e1b98715-3de7-47ed-90b5-2832b5f75c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjYzNTAsIm5iZiI6MTcxNjU2NjA1MCwicGF0aCI6Ii8xMjU5MDQ3NTYvMzMzMDk1ODk3LWUxYjk4NzE1LTNkZTctNDdlZC05MGI1LTI4MzJiNWY3NWM2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTU0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjBhNjUzNDY0Mzc3OTJhMGZmNWY5MjE1NjkwYzNmMTQ0MWQyZDZkMzFlNGQyZWFkZTExMTliZDgxNmQwOGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t0zMe89pMBx3YsTGqNaD_tblmz6Y8JMfVUgmQW4VXIg">
> 
> Hey @ashk1996 , in your example hasHint = true. In this case it looks good. But if hasHint = false and only hasError = true and errorMessage is not empty, then the error message is not left aligned but right aligned, as seen in my screenshot above.
> 
> While looking at it again, if errorMessageIcon is not undefined and errorMessage is empty, the icon should also be displayed right aligned, but currently it is not displayed at all in this case. It will only appear once errorMessage is not empty anymore.
> 
> If you want we can have a quick huddle about this :-)

Thanks for pointing out. I have fixed this in the latest commit.

2024-05-29 14:50 UTC, thrbnhrtmnn commented
Hey @ashk1996 , as discussed today the icon not being displayed if the corresponding message is empty is not an issue, because this would just be a user mistake. There should not be an icon when there is no message. Neither for errors nor for hints.

After looking again the only point I found is that in case the hasHint = true, but message and icon are empty / undefined, the counter will be left aligned. As just discussed we should fix this, as long it is not a huge effort. Again this would be an user mistake, but if we can prevent it easily we should always do so.

2024-05-29 15:13 UTC, thrbnhrtmnn approved these changes

2024-05-29 15:13 UTC, merged