Fix/831 ensure property naming number field
deven-org/boiler pull request #940
Opened 2024-02-21 08:51 UTC by JpunktWpunkt

related to #831

2024-02-21 09:13 UTC, RubirajAccenture approved these changes

2024-02-21 09:25 UTC, angsherpa456 submitted a review, later dismissed

2024-02-21 12:09 UTC, angsherpa456 submitted a review, later dismissed

2024-02-21 13:09 UTC, angsherpa456 submitted a review, later dismissed

2024-02-21 14:41 UTC, angsherpa456 approved these changes

2024-02-21 15:24 UTC, davidken91 approved these changes

2024-03-21 16:34 UTC, thrbnhrtmnn requested changes
Hey @JpunktWpunkt , the changes already look really good. I would just change a few minor things, before I will approve:
1. unitPosition should per default be "prefix" and we should not offer the "none" option
2. hasUnit please update the Description in the props panel to "Choose if component has a unit.". We should be a bit more consistent with similar props like hasLabel
3. Please align the order of the props in the props panel to the Excel (I think only unitPosition and the section "Accessibility" and "Technical Attributes" need to be adjusted)

2024-03-22 08:32 UTC, thrbnhrtmnn submitted a review, later dismissed
Storybook looks perfect now!

By the way, did you also solve https://github.com/deven-org/boiler/issues/834 with the implementation? If so, please let me know so I can close the other issue :-)

2024-03-22 08:39 UTC, JpunktWpunkt commented
> Storybook looks perfect now!
> 
> By the way, did you also solve #834 with the implementation? If so, please let me know so I can close the other issue :-)

Yes, I did :) #834 with the last commit when I check the order I saw that name was missing :)

2024-03-22 09:12 UTC, angsherpa456 commented on packages/ui-library/src/components/input-field-number/index.ts
> +                ? html` <div class="${unitClasses}">${this.unit}</div> `
Please remove the extra space on both side of html

2024-03-22 09:13 UTC, angsherpa456 commented on packages/ui-library/src/components/input-field-number/index.ts
> +        // 'prepend': this.unitPosition === 'prefix' || this.unitPosition === 'suffix',
Can this be removed?

2024-03-22 09:31 UTC, angsherpa456 commented on packages/ui-library/src/components/input-field-number/index.stories.ts
> +
Please remove this additional line.

2024-03-22 11:09 UTC, angsherpa456 approved these changes
LGTM

2024-03-22 15:12 UTC, thrbnhrtmnn submitted a review, later dismissed

2024-03-27 15:41 UTC, faselbaum approved these changes

2024-03-27 16:01 UTC, angsherpa456 approved these changes
LGTM

2024-03-27 16:05 UTC, merged