fix(ui-library): Align how Hint & Error Messages are displayed in our component examples
deven-org/boiler pull request #974
Opened 2024-03-01 11:25 UTC by RubirajAccenture

2024-03-06 10:02 UTC, thrbnhrtmnn reviewed
Hey @RubirajAccenture ,

3 ACs of the issue are not yet met when I look at the branch:
- [x]  TextInput: default error message icon is "undefined" in the Text Input
- [ ]  TextArea: default error message icon is "undefined" in the Text Area
- [ ]  Select: default error message icon is "undefined" in the Select

Also, if you added the tests to make sure, that the error message icon is always undefined per default, we should get errors for this. It seems to me that something is not working here.

2024-03-07 11:23 UTC, RubirajAccenture commented
> Hey @RubirajAccenture ,
> 
> 3 ACs of the issue are not yet met when I look at the branch:
> 
> * [ ]   TextInput: default error message icon is "undefined" in the Text Input
> * [ ]   TextArea: default error message icon is "undefined" in the Text Area
> * [ ]   Select: default error message icon is "undefined" in the Select
> 
> Also, if you added the tests to make sure, that the error message icon is always undefined per default, we should get errors for this. It seems to me that something is not working here.

Changes done

2024-03-07 14:56 UTC, angsherpa456 commented on packages/ui-library/src/components/checkbox/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
Please remove the extra space before the _error Icon_. Also would be nice to have it more contextual while reading by rephrasing it to something like **it('sets the error Icon to undefined')**.

2024-03-07 15:34 UTC, angsherpa456 commented on packages/ui-library/src/components/checkbox/index.test.ts
> +    expect(errorIcon).to.be.equal(undefined);
Could you may be check for undefined directly i.e. expect(errorIcon).beUndefined

2024-03-07 15:39 UTC, angsherpa456 commented on packages/ui-library/src/components/radio-group/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
Same as first comment.

2024-03-07 15:40 UTC, angsherpa456 commented on packages/ui-library/src/components/radio/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
same as first comment

2024-03-07 15:40 UTC, angsherpa456 commented on packages/ui-library/src/components/select/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
same as first comment

2024-03-07 15:40 UTC, angsherpa456 commented on packages/ui-library/src/components/text-input/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
same as first comment

2024-03-07 15:41 UTC, angsherpa456 commented on packages/ui-library/src/components/textarea/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
same as first comment

2024-03-07 17:20 UTC, thrbnhrtmnn reviewed
Hey @RubirajAccenture ,

I forgot to list the Number Input in the issue. Can you also add the test to the Number Input?

Also I checked the Storybook pages and found an issue in Text Input and Select, which was not appearing in develop and seems to be introduced within your branch. When hasError=true, the whole input field gets bigger and also the icon disappeared. Could you check that?

2024-03-20 16:21 UTC, thrbnhrtmnn commented
As just discussed, here are the findings that were added to the ticket:

Open points:
- Radio: Form Caption Group Example has wrong icon for hint
- Radio Group: Form Caption Group Example has missing icon for error message
- Input Field Text: ErrorMessageIcon should be undefined per default
- Text Area: ErrorMessageIcon should be undefined per default
- Input Field Number: Form Caption Group Example needs to be fixed, the Has Hint example also has a hint message and the hint & error example has a hint incl. message and icon

2024-03-20 18:22 UTC, thrbnhrtmnn requested changes
Hey @RubirajAccenture , thanks for the updates, here are my findings:
1. It seems to me that there is not yet a test for the input field number to make sure the error message icon is always undefined.
2. The Input Field Text and the Select currently get bigger in height when hasError=true, this should not happen.
3. In the Checkbox Docs, under Form Caption Group the hintMessageIcon should be blrInfo in the secon example (hint and error)

2024-03-20 18:22 UTC, thrbnhrtmnn commented on packages/ui-library/src/components/radio-group/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
This still needs to be fixed

2024-03-20 18:22 UTC, thrbnhrtmnn commented on packages/ui-library/src/components/radio/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
Please fix this

2024-03-20 18:22 UTC, thrbnhrtmnn commented on packages/ui-library/src/components/select/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
This also still needs a fix

2024-03-20 18:22 UTC, thrbnhrtmnn commented on packages/ui-library/src/components/input-field-text/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
Please remove the space before "error Icon"

2024-03-20 18:22 UTC, thrbnhrtmnn commented on packages/ui-library/src/components/textarea/index.test.ts
> +  it(' error Icon is set to undefined', async () => {
Please fix this one

2024-03-21 16:03 UTC, thrbnhrtmnn approved these changes
Hey @RubirajAccenture , all points where fixed. I approve the PR, but I also found a very minor topic. If you have time you can fix it as well to improve consistency. I will quickly approve again in case you change something.

2024-03-25 09:53 UTC, faselbaum approved these changes

2024-03-25 09:58 UTC, angsherpa456 commented on packages/ui-library/src/components/radio-group/index.test.ts
> +    const radioGroup = querySelectorDeep('textarea', element.getRootNode() as HTMLElement);
Please target the correct element, not the textarea.

2024-03-25 09:58 UTC, angsherpa456 commented on packages/ui-library/src/components/radio-group/index.test.ts
> +    expect(errorIcon).to.be.undefined;
Please adjust similar to prior tests.

2024-03-25 10:02 UTC, angsherpa456 commented on packages/ui-library/src/components/radio/index.test.ts
> +    const formCaptionError = querySelectorDeep('.blr-form-caption', formCaptions[1] as HTMLElement);
Isn't it possible to target the error inside the form-caption directly just like in other cases? The querySelectorAllDeep is useful if both the hint and error needs to be tested. 
Note: hasHint can be set to false (if not already set in sampleParams) to assure that only one icon exist inside the form-caption.

2024-03-25 10:05 UTC, angsherpa456 commented on packages/ui-library/src/components/radio/index.test.ts
> +    const errorIcon = formCaptionError?.getAttribute('errorIcon');
Please adjust this like other test because this will ends up the line 74 always being truthy.

2024-03-25 10:06 UTC, angsherpa456 commented on packages/ui-library/src/components/select/index.test.ts
> +    const labelWrapper = querySelectorDeep('.label-wrapper', element.getRootNode() as HTMLElement);
Same as above packages/ui-library/src/components/radio/index.test.ts

2024-03-25 10:06 UTC, angsherpa456 commented on packages/ui-library/src/components/textarea/index.test.ts
> +  it('error Icon is set to undefined', async () => {
Same as above packages/ui-library/src/components/radio/index.test.ts

2024-03-25 14:38 UTC, faselbaum approved these changes

2024-03-26 11:16 UTC, angsherpa456 commented
Hi @RubirajAccenture, the current test code `
const errorIcon = formCaptionError?.getAttribute('errorIcon');
expect(errorIcon).to.not.exist;` 

will end up being a dead code because this test will always be truthy as there will never exist errorIcon attribute which getAttribute is trying to get. Please fix this as suggested in my previous comments.

Secondly, the title of the tests are still mismatch, please make it consistent with 
it('has error Icon set to undefined')..

2024-03-27 09:38 UTC, closed without merging